import type { Config } from 'tailwindcss'
import animate from 'tailwindcss-animate'

const config: Config = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './.storybook/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      // ── ShadCN semantic colors (mapped to Lyra tokens in index.css) ──────
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          border: 'hsl(var(--sidebar-border))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          ring: 'hsl(var(--sidebar-ring))',
        },

        // ── Lyra semantic colors (use these in components) ──────────────
        'lyra-bg': {
          'surface-base':             'var(--lyra-color-bg-surface-base)',
          'surface-canvas':           'var(--lyra-color-bg-surface-canvas)',
          'surface-shell':            'var(--lyra-color-bg-surface-shell)',
          'surface-container':        'var(--lyra-color-bg-surface-container)',
          'surface-inverse':          'var(--lyra-color-bg-surface-inverse)',
          'primary':                  'var(--lyra-color-bg-primary)',
          'secondary':                'var(--lyra-color-bg-secondary)',
          'destructive':              'var(--lyra-color-bg-destructive)',
          'disabled':                 'var(--lyra-color-bg-disabled)',
          'field':                    'var(--lyra-color-bg-field)',
          'field-ai':                 'var(--lyra-color-bg-field-ai)',
          'active-strong':            'var(--lyra-color-bg-active-strong)',
          'active-subtle':            'var(--lyra-color-bg-active-subtle)',
        },
        'lyra-fg': {
          'default':        'var(--lyra-color-fg-default)',
          'secondary':      'var(--lyra-color-fg-secondary)',
          'disabled':       'var(--lyra-color-fg-disabled)',
          'inverse':        'var(--lyra-color-fg-inverse)',
          'link':           'var(--lyra-color-fg-link)',
          'on-primary':     'var(--lyra-color-fg-on-primary)',
          'on-destructive': 'var(--lyra-color-fg-on-destructive)',
          'action':         'var(--lyra-color-fg-action)',
          'active-strong':  'var(--lyra-color-fg-active-strong)',
        },
        'lyra-border': {
          'default':  'var(--lyra-color-border-default)',
          'subtle':   'var(--lyra-color-border-subtle)',
          'medium':   'var(--lyra-color-border-medium)',
          'strong':   'var(--lyra-color-border-strong)',
          'active':   'var(--lyra-color-border-active)',
          'disabled': 'var(--lyra-color-border-disabled)',
          'focus':    'var(--lyra-color-border-focus)',
          'field-ai': 'var(--lyra-color-border-field-ai)',
        },
        'lyra-status': {
          'critical-strong': 'var(--lyra-color-status-critical-strong)',
          'critical-medium': 'var(--lyra-color-status-critical-medium)',
          'critical-subtle': 'var(--lyra-color-status-critical-subtle)',
          'warning-strong':  'var(--lyra-color-status-warning-strong)',
          'warning-medium':  'var(--lyra-color-status-warning-medium)',
          'warning-subtle':  'var(--lyra-color-status-warning-subtle)',
          'success-strong':  'var(--lyra-color-status-success-strong)',
          'success-medium':  'var(--lyra-color-status-success-medium)',
          'success-subtle':  'var(--lyra-color-status-success-subtle)',
          'info-strong':     'var(--lyra-color-status-info-strong)',
          'info-medium':     'var(--lyra-color-status-info-medium)',
          'info-subtle':     'var(--lyra-color-status-info-subtle)',
        },
        'lyra-state': {
          'hover-opacity':          'var(--lyra-color-state-hover-opacity)',
          'hover-primary':          'var(--lyra-color-state-hover-primary)',
          'hover-secondary':        'var(--lyra-color-state-hover-secondary)',
          'hover-active-strong':    'var(--lyra-color-state-hover-active-strong)',
          'hover-active-subtle':    'var(--lyra-color-state-hover-active-subtle)',
          'hover-critical-strong':  'var(--lyra-color-state-hover-critical-strong)',
          'pressed-opacity':        'var(--lyra-color-state-pressed-opacity)',
          'pressed-primary':        'var(--lyra-color-state-pressed-primary)',
          'pressed-secondary':      'var(--lyra-color-state-pressed-secondary)',
          'pressed-active-strong':  'var(--lyra-color-state-pressed-active-strong)',
          'pressed-active-subtle':  'var(--lyra-color-state-pressed-active-subtle)',
          'pressed-critical-strong':'var(--lyra-color-state-pressed-critical-strong)',
        },
        'lyra-accent': {
          'blue-subtle':   'var(--lyra-color-accent-blue-subtle)',
          'blue-soft':     'var(--lyra-color-accent-blue-soft)',
          'blue-strong':   'var(--lyra-color-accent-blue-strong)',
          'blue-fg':       'var(--lyra-color-accent-blue-fg)',
          'green-subtle':  'var(--lyra-color-accent-green-subtle)',
          'green-soft':    'var(--lyra-color-accent-green-soft)',
          'green-strong':  'var(--lyra-color-accent-green-strong)',
          'green-fg':      'var(--lyra-color-accent-green-fg)',
          'red-subtle':    'var(--lyra-color-accent-red-subtle)',
          'red-soft':      'var(--lyra-color-accent-red-soft)',
          'red-strong':    'var(--lyra-color-accent-red-strong)',
          'red-fg':        'var(--lyra-color-accent-red-fg)',
          'yellow-soft':   'var(--lyra-color-accent-yellow-soft)',
          'yellow-strong': 'var(--lyra-color-accent-yellow-strong)',
          'yellow-fg':     'var(--lyra-color-accent-yellow-fg)',
          'orange-soft':   'var(--lyra-color-accent-orange-soft)',
          'orange-strong': 'var(--lyra-color-accent-orange-strong)',
          'orange-fg':     'var(--lyra-color-accent-orange-fg)',
          'purple-subtle': 'var(--lyra-color-accent-purple-subtle)',
          'purple-soft':   'var(--lyra-color-accent-purple-soft)',
          'purple-strong': 'var(--lyra-color-accent-purple-strong)',
          'purple-fg':     'var(--lyra-color-accent-purple-fg)',
          'teal-soft':     'var(--lyra-color-accent-teal-soft)',
          'teal-strong':   'var(--lyra-color-accent-teal-strong)',
          'teal-fg':       'var(--lyra-color-accent-teal-fg)',
          'pink-soft':     'var(--lyra-color-accent-pink-soft)',
          'pink-strong':   'var(--lyra-color-accent-pink-strong)',
          'pink-fg':       'var(--lyra-color-accent-pink-fg)',
          'lime-soft':     'var(--lyra-color-accent-lime-soft)',
          'lime-strong':   'var(--lyra-color-accent-lime-strong)',
          'lime-fg':       'var(--lyra-color-accent-lime-fg)',
          'slate-subtle':  'var(--lyra-color-accent-slate-subtle)',
          'slate-soft':    'var(--lyra-color-accent-slate-soft)',
          'slate-strong':  'var(--lyra-color-accent-slate-strong)',
          'slate-fg':      'var(--lyra-color-accent-slate-fg)',
        },

        // ── Lyra base color palette ───────────────────────────────────────
        lyra: {
          brand: {
            25:  'var(--lyra-brand-25)',
            50:  'var(--lyra-brand-50)',
            100: 'var(--lyra-brand-100)',
            200: 'var(--lyra-brand-200)',
            300: 'var(--lyra-brand-300)',
            400: 'var(--lyra-brand-400)',
            500: 'var(--lyra-brand-500)',
            600: 'var(--lyra-brand-600)',
            700: 'var(--lyra-brand-700)',
            800: 'var(--lyra-brand-800)',
            900: 'var(--lyra-brand-900)',
            950: 'var(--lyra-brand-950)',
          },
          blue: {
            25:  'var(--lyra-blue-25)',
            50:  'var(--lyra-blue-50)',
            100: 'var(--lyra-blue-100)',
            200: 'var(--lyra-blue-200)',
            300: 'var(--lyra-blue-300)',
            400: 'var(--lyra-blue-400)',
            500: 'var(--lyra-blue-500)',
            600: 'var(--lyra-blue-600)',
            700: 'var(--lyra-blue-700)',
            800: 'var(--lyra-blue-800)',
            900: 'var(--lyra-blue-900)',
            950: 'var(--lyra-blue-950)',
          },
          gray: {
            25:  'var(--lyra-gray-25)',
            50:  'var(--lyra-gray-50)',
            100: 'var(--lyra-gray-100)',
            200: 'var(--lyra-gray-200)',
            300: 'var(--lyra-gray-300)',
            400: 'var(--lyra-gray-400)',
            500: 'var(--lyra-gray-500)',
            600: 'var(--lyra-gray-600)',
            700: 'var(--lyra-gray-700)',
            800: 'var(--lyra-gray-800)',
            900: 'var(--lyra-gray-900)',
            950: 'var(--lyra-gray-950)',
          },
          slate: {
            25:  'var(--lyra-slate-25)',
            50:  'var(--lyra-slate-50)',
            100: 'var(--lyra-slate-100)',
            200: 'var(--lyra-slate-200)',
            300: 'var(--lyra-slate-300)',
            400: 'var(--lyra-slate-400)',
            500: 'var(--lyra-slate-500)',
            600: 'var(--lyra-slate-600)',
            700: 'var(--lyra-slate-700)',
            800: 'var(--lyra-slate-800)',
            900: 'var(--lyra-slate-900)',
            950: 'var(--lyra-slate-950)',
          },
          green: {
            25:  'var(--lyra-green-25)',
            50:  'var(--lyra-green-50)',
            100: 'var(--lyra-green-100)',
            200: 'var(--lyra-green-200)',
            300: 'var(--lyra-green-300)',
            400: 'var(--lyra-green-400)',
            500: 'var(--lyra-green-500)',
            600: 'var(--lyra-green-600)',
            700: 'var(--lyra-green-700)',
            800: 'var(--lyra-green-800)',
            900: 'var(--lyra-green-900)',
            950: 'var(--lyra-green-950)',
          },
          red: {
            25:  'var(--lyra-red-25)',
            50:  'var(--lyra-red-50)',
            100: 'var(--lyra-red-100)',
            200: 'var(--lyra-red-200)',
            300: 'var(--lyra-red-300)',
            400: 'var(--lyra-red-400)',
            500: 'var(--lyra-red-500)',
            600: 'var(--lyra-red-600)',
            700: 'var(--lyra-red-700)',
            800: 'var(--lyra-red-800)',
            900: 'var(--lyra-red-900)',
            950: 'var(--lyra-red-950)',
          },
          yellow: {
            25:  'var(--lyra-yellow-25)',
            50:  'var(--lyra-yellow-50)',
            100: 'var(--lyra-yellow-100)',
            200: 'var(--lyra-yellow-200)',
            300: 'var(--lyra-yellow-300)',
            400: 'var(--lyra-yellow-400)',
            500: 'var(--lyra-yellow-500)',
            600: 'var(--lyra-yellow-600)',
            700: 'var(--lyra-yellow-700)',
            800: 'var(--lyra-yellow-800)',
            900: 'var(--lyra-yellow-900)',
            950: 'var(--lyra-yellow-950)',
          },
          orange: {
            25:  'var(--lyra-orange-25)',
            50:  'var(--lyra-orange-50)',
            100: 'var(--lyra-orange-100)',
            200: 'var(--lyra-orange-200)',
            300: 'var(--lyra-orange-300)',
            400: 'var(--lyra-orange-400)',
            500: 'var(--lyra-orange-500)',
            600: 'var(--lyra-orange-600)',
            700: 'var(--lyra-orange-700)',
            800: 'var(--lyra-orange-800)',
            900: 'var(--lyra-orange-900)',
            950: 'var(--lyra-orange-950)',
          },
          purple: {
            25:  'var(--lyra-purple-25)',
            50:  'var(--lyra-purple-50)',
            100: 'var(--lyra-purple-100)',
            200: 'var(--lyra-purple-200)',
            300: 'var(--lyra-purple-300)',
            400: 'var(--lyra-purple-400)',
            500: 'var(--lyra-purple-500)',
            600: 'var(--lyra-purple-600)',
            700: 'var(--lyra-purple-700)',
            800: 'var(--lyra-purple-800)',
            900: 'var(--lyra-purple-900)',
            950: 'var(--lyra-purple-950)',
          },
          teal: {
            25:  'var(--lyra-teal-25)',
            50:  'var(--lyra-teal-50)',
            100: 'var(--lyra-teal-100)',
            200: 'var(--lyra-teal-200)',
            300: 'var(--lyra-teal-300)',
            400: 'var(--lyra-teal-400)',
            500: 'var(--lyra-teal-500)',
            600: 'var(--lyra-teal-600)',
            700: 'var(--lyra-teal-700)',
            800: 'var(--lyra-teal-800)',
            900: 'var(--lyra-teal-900)',
            950: 'var(--lyra-teal-950)',
          },
          pink: {
            25:  'var(--lyra-pink-25)',
            50:  'var(--lyra-pink-50)',
            100: 'var(--lyra-pink-100)',
            200: 'var(--lyra-pink-200)',
            300: 'var(--lyra-pink-300)',
            400: 'var(--lyra-pink-400)',
            500: 'var(--lyra-pink-500)',
            600: 'var(--lyra-pink-600)',
            700: 'var(--lyra-pink-700)',
            800: 'var(--lyra-pink-800)',
            900: 'var(--lyra-pink-900)',
            950: 'var(--lyra-pink-950)',
          },
          lime: {
            25:  'var(--lyra-lime-25)',
            50:  'var(--lyra-lime-50)',
            100: 'var(--lyra-lime-100)',
            200: 'var(--lyra-lime-200)',
            300: 'var(--lyra-lime-300)',
            400: 'var(--lyra-lime-400)',
            500: 'var(--lyra-lime-500)',
            600: 'var(--lyra-lime-600)',
            700: 'var(--lyra-lime-700)',
            800: 'var(--lyra-lime-800)',
            900: 'var(--lyra-lime-900)',
            950: 'var(--lyra-lime-950)',
          },
          white: 'var(--lyra-white)',
          black: 'var(--lyra-black)',
        },
      },

      // ── Border radius (Lyra lyra/radius/*) ───────────────────────────────
      borderRadius: {
        none:  'var(--lyra-radius-none)',
        '2xs': 'var(--lyra-radius-2xs)',
        xs:    'var(--lyra-radius-xs)',
        sm:    'var(--lyra-radius-sm)',
        DEFAULT: 'var(--lyra-radius-md)',
        md:    'var(--lyra-radius-md)',
        lg:    'var(--lyra-radius-lg)',
        xl:    'var(--lyra-radius-xl)',
        round: 'var(--lyra-radius-round)',
        full:  '9999px',
      },

      // ── Spacing extras (Lyra lyra/spacing/*) ─────────────────────────────
      spacing: {
        '0.5px': 'var(--lyra-spacing-05)',
      },

      // ── Font sizes (Lyra lyra/base/typography/size/*) ─────────────────────
      fontSize: {
        'lyra-xs':   ['var(--lyra-text-xs)',   { lineHeight: 'var(--lyra-leading-tight)' }],
        'lyra-sm':   ['var(--lyra-text-sm)',   { lineHeight: 'var(--lyra-leading-normal)' }],
        'lyra-base': ['var(--lyra-text-base)', { lineHeight: 'var(--lyra-leading-normal)' }],
        'lyra-xl':   ['var(--lyra-text-xl)',   { lineHeight: 'var(--lyra-leading-loose)' }],
      },

      // ── Font weights ──────────────────────────────────────────────────────
      fontWeight: {
        'lyra-regular':  'var(--lyra-weight-regular)',
        'lyra-semibold': 'var(--lyra-weight-semibold)',
        'lyra-bold':     'var(--lyra-weight-bold)',
      },

      // ── Component size utilities ──────────────────────────────────────────
      height: {
        'control-xs': 'var(--lyra-control-xs)',
        'control-sm': 'var(--lyra-control-sm)',
        'control-md': 'var(--lyra-control-md)',
        'control-lg': 'var(--lyra-control-lg)',
        'control-xl': 'var(--lyra-control-xl)',
        'row-sm':  'var(--lyra-row-sm)',
        'row-md':  'var(--lyra-row-md)',
        'row-lg':  'var(--lyra-row-lg)',
        'row-xl':  'var(--lyra-row-xl)',
        'row-2xl': 'var(--lyra-row-2xl)',
        'bar-sm':  'var(--lyra-bar-sm)',
        'bar-md':  'var(--lyra-bar-md)',
      },

      // ── Icon size utilities ───────────────────────────────────────────────
      width: {
        'icon-xs': 'var(--lyra-icon-xs)',
        'icon-sm': 'var(--lyra-icon-sm)',
        'icon-md': 'var(--lyra-icon-md)',
        'icon-lg': 'var(--lyra-icon-lg)',
      },

      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [animate],
}

export default config
